SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK_SALES BS
JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE YEAR(BS.SALES_DATE) = 2022 AND MONTH(BS.SALES_DATE) = 1
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;


# SELECT price * sales as TOTAL_SALES, b.AUTHOR_ID, 
# FROM BOOK_SALES bs JOIN BOOK b ON bs.book_id = b.book_id
# WHERE MONTH(bs.sales_date) = 1
# GROUP BY b.book_id;