# SELECT * FROM CAR_RENTAL_COMPANY_CAR;

# SELECT * FROM CAR_RENTAL_COMPANY_CAR WHERE car_type = 'SUV';

SELECT ROUND(AVG(daily_fee)) as AVERAGE_FEE FROM CAR_RENTAL_COMPANY_CAR WHERE car_type = 'SUV';