# SELECT *
# FROM ONLINE_SALE
# WHERE USER_ID IN (
#     SELECT USER_ID, PRODUCT_ID, COUNT(*) AS CNT
#     FROM ONLINE_SALE
#     GROUP BY USER_ID, PRODUCT_ID
#     HAVING CNT >= 2
# )
# ;

# USER_ID, PRODUCT_ID, COUNT(SALES_AMOUNT) AS CNT

SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(SALES_AMOUNT) >= 2
ORDER BY 1, 2 DESC
;