-- 코드를 입력하세요

WITH TEMP AS (
    SELECT PRODUCT_ID, PRODUCT_CODE, SUM(SALES_AMOUNT) 판매량, PRICE
    FROM PRODUCT JOIN OFFLINE_SALE USING (PRODUCT_ID)
    GROUP BY PRODUCT_ID
    ORDER BY 1
)
SELECT PRODUCT_CODE, 판매량 * PRICE AS SALES
FROM TEMP
ORDER BY 2 DESC, 1;
