WITH RENTAL_HISTORY AS (
    SELECT 
        HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_DAYS, 
        CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상' 
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상' END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
    
SELECT RH.HISTORY_ID,
CASE
    WHEN RH.DURATION_TYPE IS NULL THEN ROUND(RH.RENTAL_DAYS * C.DAILY_FEE)
    ELSE ROUND(RH.RENTAL_DAYS * C.DAILY_FEE * (100 - DP.DISCOUNT_RATE) / 100)
    END AS FEE
FROM RENTAL_HISTORY RH
    JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = RH.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
        ON RH.DURATION_TYPE = DP.DURATION_TYPE AND DP.CAR_TYPE = '트럭'
WHERE C.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC
;