-- JULY PK = SHIPMENT, FK = FLAVOR
-- FIRST HALF PK = FLAVOR, FK = SHIPMENT

-- 7월 맛 별 아이스크림 총 주문량
# SELECT FLAVOR, SUM(TOTAL_ORDER)
# FROM JULY J
# GROUP BY FLAVOR
# ;

-- 이녀석과 상반기를 조인
SELECT FH.FLAVOR
FROM FIRST_HALF FH
    LEFT JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
        FROM JULY
        GROUP BY FLAVOR
    ) AS JULY ON FH.FLAVOR = JULY.FLAVOR
ORDER BY FH.TOTAL_ORDER + JULY.TOTAL DESC
LIMIT 3
;