-- 2022년 1월의 카테고리 별 도서 판매량 합산

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES S
    JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY B.CATEGORY
ORDER BY 1
;

